 * Serving Flask app 'mock_api'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
[33mPress CTRL+C to quit[0m
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 835-442-656
Traceback (most recent call last):
  File "/Users/akshaykumaran/RetailSync-Secure-Multi-Tenant-Real-Time-Retail-Database-Architecture/backend/mock_api.py", line 675, in <module>
    app.run(debug=True, port=5002)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 1097, in run_simple
    run_with_reloader(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/_reloader.py", line 446, in run_with_reloader
    ensure_echo_on()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/_reloader.py", line 426, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
